// SELLERS
export const GET_SELLERS = 'GET_SELLERS';
export const SET_SELLERS = 'SET_SELLERS';
export const SET_SELLERS_FAILED = 'SET_SELLERS_FAILED';

// BOOKINGS
export const GET_BOOKINGS = 'GET_BOOKINGS';
export const SET_BOOKINGS = 'SET_BOOKINGS';
export const SET_GROUPED_BOOKINGS = 'SET_GROUPED_BOOKINGS';
export const SET_BOOKINGS_FAILED = 'SET_BOOKINGS_FAILED';

// PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCTS_FAILED = 'SET_PRODUCTS_FAILED';
